### ISSUE TITLE
Odin: Extract/Compress missing from context menu

### ISSUE THREAD

**Issue by marbetschar** [elementary/file-roller-contract#1]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

A right click on a ZIP file used to provide the "Extract" option in the context menu on Hera. This does no longer work in Odin. Same is true for "Compress", which enabled us to create a ZIP file from selected files.

Here a Screenshot of the missing "Extract" option:

![IMG_5221](https://user-images.githubusercontent.com/392542/94681167-47e71f80-0323-11eb-893d-0b52a7aa398f.jpeg)

## Platform Information

![Screenshot from 2020-09-30 13-46-46](https://user-images.githubusercontent.com/392542/94681247-677e4800-0323-11eb-80c9-16ee531e936b.png)

- [x] I'm using the latest version from daily

**Comment by worldofpeace** [comment]
It would be useful to get logging from the contractor service. Like, is it even enumerating the files that have the contract that sets this up.

**Comment by marbetschar** [comment]
@worldofpeace I'd love to fix this, but I don't know where/how to start. Any hints how to kick things off?

**UPDATE:** Seems like the contracts are not installed on my machine (see below). Will this be fixed if I just install a newer daily build?

```
/usr/share/contractor$ ls -latrh
total 28K
-rw-r--r--   1 root root  139 Mär  8  2019 io.elementary.print.contract
-rw-r--r--   1 root root  259 Nov 11 22:05 com.github.artemanufrij.imageburner.contract
-rw-r--r--   1 root root  341 Dez  6 22:46 set-wallpaper.contract
```

**Comment by queeup** [comment]
`# apt install io.elementary.contractor.file-roller`
